INSERT INTO players (name) VALUES ('Ivan');
INSERT INTO players (name) VALUES ('Pavel');
INSERT INTO players (name) VALUES ('Dmitry');
INSERT INTO players (name) VALUES ('Sergey');
INSERT INTO players (name) VALUES ('Valeriy');
INSERT INTO players (name) VALUES ('Igor');
INSERT INTO players (name) VALUES ('Petr');
INSERT INTO players (name) VALUES ('Alexey');
INSERT INTO matches (player1, player2, winner) VALUES (1, 2, 1);
INSERT INTO matches (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO matches (player1, player2, winner) VALUES (5, 6, 6);
INSERT INTO matches (player1, player2, winner) VALUES (7, 8, 6);
INSERT INTO matches (player1, player2, winner) VALUES (1, 3, 3);
INSERT INTO matches (player1, player2, winner) VALUES (2, 5, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 6, 3);
INSERT INTO matches (player1, player2, winner) VALUES (1, 4, 1);
INSERT INTO matches (player1, player2, winner) VALUES (1, 5, 1);
INSERT INTO matches (player1, player2, winner) VALUES (2, 7, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 8, 8);
INSERT INTO matches (player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO matches (player1, player2, winner) VALUES (4, 7, 4);
INSERT INTO matches (player1, player2, winner) VALUES (4, 6, 6);
INSERT INTO matches (player1, player2, winner) VALUES (3, 5, 5);
INSERT INTO matches (player1, player2, winner) VALUES (1, 8, 8);
INSERT INTO matches (player1, player2, winner) VALUES (7, 5, 5);
INSERT INTO matches (player1, player2, winner) VALUES (1, 5, 5);
INSERT INTO matches (player1, player2, winner) VALUES (1, 6, 6);